### ISSUE TITLE
Custom Data class coder problem

### ISSUE THREAD

**Issue by DopingDeveloper** [swsnu/bd2017#14]
HW2 과제 중에 제가 data 처리를 위해 Data class를 하나 생성하였습니다.
그러고 나서 실행을 해보니 해당 class를 처리하기 위한 coder가 없다고 하여 CustomCoder를 생성하는 부분을 찾아보고 있는데요. 
자세하게 설명된 부분을 찾기 어려워 진행에 어려움이 생겼습니다. 혹시 참조할만한 문서가 있는지 알고싶습니다.

**Comment by johnyangk** [comment]
vortex_runtime의 PairCoder를 참고하시면 좋을 것 같습니다.

**Comment by DopingDeveloper** [comment]
CustomCoder를 생성해서 GroupbyKey를 적용하면 다음과 같은 에러가 발생합니다.

Exception in thread "main" java.lang.IllegalStateException: the keyCoder of a GroupByKey must be deterministic
        at org.apache.beam.sdk.transforms.GroupByKey.expand(GroupByKey.java:212)
        at org.apache.beam.sdk.transforms.GroupByKey.expand(GroupByKey.java:120)
        at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:482)
        at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:422)
        at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:277)
        at EPLAnalyzer.main(EPLAnalyzer.java:288)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.beam.sdk.coders.Coder$NonDeterministicException: org.apache.beam.sdk.coders.SerializableCoder@3214ee6 is not deterministic because:
  Java Serialization may be non-deterministic.
        at org.apache.beam.sdk.coders.SerializableCoder.verifyDeterministic(SerializableCoder.java:152)
        at org.apache.beam.sdk.transforms.GroupByKey.expand(GroupByKey.java:210)
        ... 14 more

해결방법이 있을까요?
데이터는 KV<Pair<String, String>, Long>으로 입력하였습니다.

**Comment by DopingDeveloper** [comment]
해당 문제를 살펴보니 Pair class가 GroupBy에서 정상적으로 작동하지 않는것으로 파악이 되었습니다.
제가 사용했던 Pair Class는 apache.Beam에서 제공되는 것인데 다른 문제점을 파악하고 해결이 되면 이슈에 덧붙이겠습니다.

**Comment by junggil** [comment]
경우는 조금 다른 것 같은데 제가 겪은 내용을 공유 하자면, 
저는 Set\<String\>를 Key로 사용했었는데 not deterministic하다는 에러가 발생해서, 
Key를 Sorting한 List\<String\>으로 Key를 변경하니 관련 에러가 사라졌었습니다. 

순서가 deterministic하지 않은 부분이 있는지 찾아보면 어떨까 싶습니다.

**Comment by johnyangk** [comment]
네 deterministic key와 관련된 것 같습니다.
