### ISSUE TITLE
HW2, Vortex illegal transition error

### ISSUE THREAD

**Issue by yj-yu** [swsnu/bd2017#15]
안녕하세요. spark에서는 되는데 vortex에서 에러가 나서 진행이 안되어 도움을 구하고자 이슈를 올립니다.

Illegal transition error가 자꾸 뜨는데요,,

INFO: The Job mr_default is running.
Oct 15, 2017 10:00:54 PM org.apache.reef.client.DriverLauncher$FailedJobHandler onNext
SEVERE: Received an error for job mr_default
Exception in thread "main" java.lang.RuntimeException: edu.snu.vortex.runtime.exception.IllegalStateTransitionException: java.lang.Exception: Illegal transition from FAILED_UNRECOVERABLE[Task group failed, and is unrecoverable. The $
ob will fail.] to FAILED_RECOVERABLE[Task group failed, but is recoverable.]
Possible transitions from the current state are
at edu.snu.vortex.client.JobLauncher.main(JobLauncher.java:83)
Caused by: edu.snu.vortex.runtime.exception.IllegalStateTransitionException: java.lang.Exception: Illegal transition from FAILED_UNRECOVERABLE[Task group failed, and is unrecoverable. The job will fail.] to FAILED_RECOVERABLE[Task g$
oup failed, but is recoverable.]
Possible transitions from the current state are
at edu.snu.vortex.common.StateMachine.setState(StateMachine.java:81)
at edu.snu.vortex.runtime.master.JobStateManager.onTaskGroupStateChanged(JobStateManager.java:387)
        at edu.snu.vortex.runtime.master.scheduler.BatchScheduler.onTaskGroupStateChanged(BatchScheduler.java:134)
        at edu.snu.vortex.runtime.master.scheduler.BatchScheduler.lambda$onExecutorRemoved$6(BatchScheduler.java:311)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at edu.snu.vortex.runtime.master.scheduler.BatchScheduler.onExecutorRemoved(BatchScheduler.java:310)
        at edu.snu.vortex.runtime.master.VortexDriver$FailedEvaluatorHandler.lambda$onNext$0(VortexDriver.java:158)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at edu.snu.vortex.runtime.master.VortexDriver$FailedEvaluatorHandler.onNext(VortexDriver.java:155)
        at edu.snu.vortex.runtime.master.VortexDriver$FailedEvaluatorHandler.onNext(VortexDriver.java:151)
        at org.apache.reef.runtime.common.driver.evaluator.IdlenessCallbackEventHandler.onNext(IdlenessCallbackEventHandler.java:46)
        at org.apache.reef.runtime.common.utils.BroadCastEventHandler.onNext(BroadCastEventHandler.java:40)
        at org.apache.reef.util.ExceptionHandlingEventHandler.onNext(ExceptionHandlingEventHandler.java:46)
        at org.apache.reef.runtime.common.utils.DispatchingEStage$1.onNext(DispatchingEStage.java:72)
        at org.apache.reef.runtime.common.utils.DispatchingEStage$1.onNext(DispatchingEStage.java:69)
        at org.apache.reef.wake.impl.ThreadPoolStage$1.run(ThreadPoolStage.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Illegal transition from FAILED_UNRECOVERABLE[Task group failed, and is unrecoverable. The job will fail.] to FAILED_RECOVERABLE[Task group failed, but is recoverable.]
Possible transitions from the current state are

혹시 이러한 문제를 경험해 보시거나 관련된 full log등을 확인하는 곳을 알려주시면 감사하겠습니다.

무슨 문제일까요..

**Comment by johnyangk** [comment]
주로 사용자가 작성하는 User Defined Function(UDF)에서 exception이 나면 저 에러가 발생하는 것으로 알고 있습니다. 

다음의 방법들을 시도해보셔도 좋습니다
* spark_apps에서 exception이 안나는지 확인
* UDF 내에서 try-catch를 하고 catch안에서 로그를 낸다음에 evaluator.stderr에 관련 로그가 있는지 확인

위의 방법들을 해도 계속 에러가 나오면, 이렇게 작업한 과정들을 리포트에 적어주시면 됩니다.

**Comment by bgchun** [comment]
@yj-yu @johnyangk 이 이야기 한 대로 해 주어요. 그리고, 정확하게 어떻게 이 문제를 reproduce할 수 있는지 적어 주면 됩니다. 

@johnyangk 혹시 log 중에 확인해서 유용할 만한 정보가 있으면 추가로 알려 주어요.
