### ISSUE TITLE
HW2, Vortex free port error

### ISSUE THREAD

**Issue by junggil** [swsnu/bd2017#16]
아래와 같이 free port가 없다는 에러를 보게됩니다.
재부팅을 하면 증상이 사라지지만 작업이 중단되고, 시간이 많이 걸려서 그 외에 다른  해결 방법을 찾고 싶습니다.

```
SEVERE: Cannot find a free port with RangeTcpPortProvider{portRangeBegin=10000, portRangeCount=10000, portRangeTryCount=1000}

org.apache.reef.wake.remote.transport.exception.TransportRuntimeException: tcpPortProvider failed to return free ports.
	at org.apache.reef.wake.remote.transport.netty.NettyMessagingTransport.<init>(NettyMessagingTransport.java:188)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.reef.tang.implementation.java.InjectorImpl.injectFromPlan(InjectorImpl.java:637)
	at org.apache.reef.tang.implementation.java.InjectorImpl.getInstance(InjectorImpl.java:515)
	at org.apache.reef.tang.implementation.java.InjectorImpl.getInstance(InjectorImpl.java:533)
	at org.apache.reef.wake.remote.transport.netty.MessagingTransportFactory.newInstance(MessagingTransportFactory.java:133)
	at org.apache.reef.wake.remote.impl.DefaultRemoteManagerImplementation.<init>(DefaultRemoteManagerImplementation.java:93)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.reef.tang.implementation.java.InjectorImpl.injectFromPlan(InjectorImpl.java:637)
	at org.apache.reef.tang.implementation.java.InjectorImpl.injectFromPlan(InjectorImpl.java:661)
	at org.apache.reef.tang.implementation.java.InjectorImpl.injectFromPlan(InjectorImpl.java:625)
	at org.apache.reef.tang.implementation.java.InjectorImpl.injectFromPlan(InjectorImpl.java:625)
	at org.apache.reef.tang.implementation.java.InjectorImpl.injectFromPlan(InjectorImpl.java:661)
	at org.apache.reef.tang.implementation.java.InjectorImpl.injectFromPlan(InjectorImpl.java:625)
	at org.apache.reef.tang.implementation.java.InjectorImpl.injectFromPlan(InjectorImpl.java:661)
	at org.apache.reef.tang.implementation.java.InjectorImpl.injectFromPlan(InjectorImpl.java:625)
	at org.apache.reef.tang.implementation.java.InjectorImpl.getInstance(InjectorImpl.java:515)
	at org.apache.reef.tang.implementation.java.InjectorImpl.getInstance(InjectorImpl.java:533)
	at org.apache.reef.client.DriverLauncher.getLauncher(DriverLauncher.java:90)
	at edu.snu.vortex.client.JobLauncher.main(JobLauncher.java:80)
Caused by: java.lang.IllegalStateException: tcpPortProvider cannot find a free port.
	at org.apache.reef.wake.remote.transport.netty.NettyMessagingTransport.<init>(NettyMessagingTransport.java:172)
	... 25 more```

**Comment by johnyangk** [comment]
REEF networking에 버그가 있습니다.
재부팅 또는 wifi를 끄고 실행하는 방법이 있습니다.

**Comment by junggil** [comment]
wifi 설정으로도 해결 가능하군요. 
감사합니다. 도움이 많이 될 것 같습니다.

**Comment by bgchun** [comment]
wifi는 local address를 out-dated address를 가지고 현상에 temporary solution이 됩니다. 
이 경우에는 vortex 에서 사용하는 networking code에서 socket property를 제대로 설정하지 않아서 발생하는 것 같아요. socket property가 제대로 사용되지 않은 상태에서 수행하는 job이 제대로 socket을 닫지 않고 shutdown되거나 아니면 kill 되는 것이 반복되면서 가용 port를 붙잡고 있어서 그렇습니다. rebooting을 하면 kernel의 state를 reset하니까 다시 port를 열 수 있는 것이구요.
